version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: iloveshopping-db
    environment:
      POSTGRES_DB: iloveshopping_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kvit@psql
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iloveshopping-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/iloveshopping_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: kvit@psql
      GOOGLE_RECAPTCHA_SECRET: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
    depends_on:
      postgres-db:
        condition: service_healthy

volumes:
  pgdata: